### ISSUE TITLE
Chapter 5, would it be better to use a case study that involves point estimation instead of a hypothesis testing problem? 

### ISSUE THREAD

**Issue by lmiratrix** [jepusto/Designing-Simulations-in-R#11]
From James email. 

Luke thoughts: Point estimation is cannon.  Hypothesis testing sets stage for power.   For chapter 5, we haven't gotten to performance metrics in earnest, so hypothesis testing seems easier to navigate?  

We should first make a spreadsheet of our case studies so we can have a sense of what they are.  (Did we do this already once upon a time?)

**Comment by jepusto** [comment]
Seems reasonable to stick with hypothesis testing. 

I don't think we've done a spreadsheet of the case studies.
