### ISSUE TITLE
Disconnect the fork with bookdown main?

### ISSUE THREAD

**Issue by lmiratrix** [jepusto/Designing-Simulations-in-R#12]
In github we have the following message:

This branch is [56 commits ahead of](https://github.com/jepusto/Designing-Simulations-in-R/compare/rstudio%3Abookdown-demo%3Amain...JEP-edits), [15 commits behind](https://github.com/jepusto/Designing-Simulations-in-R/compare/JEP-edits...rstudio%3Abookdown-demo%3Amain) rstudio/bookdown-demo:main.

Do we want to disconnect so branches are relative to _our_ main, not bookdown?  Or how can we make that better?

**Comment by jepusto** [comment]
Disconnecting would be great, but I'm not sure how to do this.

**Comment by jepusto** [comment]
I put in a GitHub support ticket to detach the repo from its parent. Evidently they do a manual review for this type of request.

**Comment by jepusto** [comment]
They took care of this quickly!
